In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print (type( b))
print (b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [4]:
# getters and Slicing
Array2D = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(Array2D[1,2]) # Printing specific element
print(Array2D[1,:]) # printing specific Row
print(Array2D[:,2]) # printing specific Col


8
[6 7 8 9 0]
[3 8]


In [5]:
# numpy array is mutable
Array2D[0,2] = 20
Array2D[0,:] = 5 # changes full row to 5
Array2D[0,:] = [1,2,3,4,5] # changes row to assigned list
# same goes for column
Array2D


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [6]:
# playing  with 3D array
Array3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(Array3D.shape)
print(Array3D)

print('Slicing 01\n' , Array3D[:,:,1])
print('Slicing 02\n' , Array3D[:,1,:])
print('Slicing 03\n' , Array3D[1,:,:])



(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slicing 01
 [[ 2  5]
 [ 8 11]]
Slicing 02
 [[ 4  5  6]
 [10 11 12]]
Slicing 03
 [[ 7  8  9]
 [10 11 12]]


In [7]:
# all 1s, 0s matrics
print(np.zeros((2, 2), dtype="int32"))
print(np.ones((2, 2), dtype="float16"))

# full
print(np.full(Array3D.shape, 69, "float32"))

# identity matrix
print(np.identity(4,dtype='int16'))

[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
[[[69. 69. 69.]
  [69. 69. 69.]]

 [[69. 69. 69.]
  [69. 69. 69.]]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [8]:
# random value matrix
print(np.random.rand(3,2))
print(np.random.randint(-4,8,size=(3,2)))


[[0.79332857 0.84099726]
 [0.2266515  0.591501  ]
 [0.21824197 0.03862675]]
[[-1 -1]
 [-1  6]
 [ 5  1]]


In [9]:
# Repeat array
repeatingArray = np.array([[[1,2],[3,4]]])
print('axis 0')
print(np.repeat(repeatingArray,2,axis=0))
print('\naxis 1')
print(np.repeat(repeatingArray,2,axis=1))
print('\naxis 2')
print(np.repeat(repeatingArray,2,axis=2))


axis 0
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

axis 1
[[[1 2]
  [1 2]
  [3 4]
  [3 4]]]

axis 2
[[[1 1 2 2]
  [3 3 4 4]]]


In [10]:
# copy
justAnArray = np.random.randint(0,3,(2,2))
RefCopied = justAnArray
ValueCopied = justAnArray.copy()
RefCopied[0,0] = 69
print(justAnArray,'\n',RefCopied,'\n',ValueCopied)



[[69  1]
 [ 1  1]] 
 [[69  1]
 [ 1  1]] 
 [[2 1]
 [1 1]]


In [28]:
# mathematic Uses
dummy1 = np.random.randint(0,9,(3,3))
dummy2 = np.random.randint(0,9,(3,3))
print(dummy1)
print('Substraction:\n',dummy1 - 1)
print('Multiplication:\n',dummy1 *dummy2)

print(dummy1)
dummySin = np.sin(dummy1)
print(dummySin)
print(np.arcsin(dummySin))



[[6 7 8]
 [4 0 0]
 [0 4 4]]
Substraction:
 [[ 5  6  7]
 [ 3 -1 -1]
 [-1  3  3]]
Multiplication:
 [[12 35 48]
 [ 8  0  0]
 [ 0 32  0]]
[[6 7 8]
 [4 0 0]
 [0 4 4]]
[[-0.2794155   0.6569866   0.98935825]
 [-0.7568025   0.          0.        ]
 [ 0.         -0.7568025  -0.7568025 ]]
[[-0.28318531  0.71681469  1.42477796]
 [-0.85840735  0.          0.        ]
 [ 0.         -0.85840735 -0.85840735]]


In [17]:
# linear Algebra -> linalg
identityMat = np.identity(3,'int16')
print(np.linalg.det(identityMat))
print(np.linalg.inv(identityMat))
...

1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Statistics
stats = np.random.randint(0,9,(3,3))
print(stats)
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

[[0 2 5]
 [5 5 8]
 [5 6 1]]
0
8
37
True


In [56]:
# Reorganizing Array
beforeReshaping = np.random.randint(0,9,(2,4))
print(beforeReshaping.shape)
afterReshaping = beforeReshaping.reshape(8,1)
print(afterReshaping.shape)
# reshaping possible if shaping elements matches with elements of the required shape
# like 4 x 2 = 2 x 2 x 2 = 8 x 1 = 2 x 4 

# Vertical and Horizontal Statking
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
vstk = np.vstack([a1,a2])
hstk = np.hstack((a1,a2))
print('vt1\n',vstk)
print('ht1\n',hstk)
h1 = np.ones(shape=(2,4))
h2 = np.zeros(shape=(2,2))
h3 = np.ones(shape=(3,2))
print('ht2\n',np.hstack([h1,h2]))
print('vt2\n',np.vstack([h3,h2]))

# change datatype
print('int to float :\n',a1.astype('float16'))


(2, 4)
(8, 1)
vt1
 [[1 2 3 4]
 [5 6 7 8]]
ht1
 [1 2 3 4 5 6 7 8]
ht2
 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
vt2
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
int to float :
 [1. 2. 3. 4.]


In [86]:
# Advance Indexing and Boolean Masking

data = np.random.randint(0, 9, (4, 5))

print(data)
print(data > 5)
print(data[data > 5])

print(data[[0, 2], [1, 3]])  # 0th row 1st col and 2nd row 3rd col

print(np.any(data>6,axis=0))# any value of a col is greater than 6 then true
print(np.any(data>6,axis=1))# any value of a row is greater than 6 then true

print(np.all(data>6,axis=1))# all values of a row is greater than 6 then true

print('\n',(data >5 ) & (data<7))


[[6 7 4 8 3]
 [6 5 6 0 0]
 [5 7 5 3 4]
 [0 6 7 2 4]]
[[ True  True False  True False]
 [ True False  True False False]
 [False  True False False False]
 [False  True  True False False]]
[6 7 8 6 6 7 6 7]
[7 3]
[False  True  True  True False]
[ True False  True  True]
[False False False False]

 [[ True False False False False]
 [ True False  True False False]
 [False False False False False]
 [False  True False False False]]


In [91]:
# Read Data from File

data = np.genfromtxt('./Numpy_Data.txt',dtype='int16',delimiter=',')
data.cumsum(axis=0,dtype='int32')


array([[ 3,  2,  5,  4,  6,  5],
       [ 7, 10, 11,  7, 10, 10],
       [14, 15, 12,  7, 14, 18]])