In [52]:
import numpy as np

In [53]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print (type( b))
print (b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
int32


In [54]:
# getters and Slicing
Array2D = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(Array2D[1,2]) # Printing specific element
print(Array2D[1,:]) # printing specific Row
print(Array2D[:,2]) # printing specific Col


8
[6 7 8 9 0]
[3 8]


In [55]:
# numpy array is mutable
Array2D[0,2] = 20
Array2D[0,:] = 5 # changes full row to 5
Array2D[0,:] = [1,2,3,4,5] # changes row to assigned list
# same goes for column
Array2D


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [56]:
# playing  with 3D array
Array3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(Array3D.shape)
print(Array3D)

print('Slicing 01\n' , Array3D[:,:,1])
print('Slicing 02\n' , Array3D[:,1,:])
print('Slicing 03\n' , Array3D[1,:,:])



(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slicing 01
 [[ 2  5]
 [ 8 11]]
Slicing 02
 [[ 4  5  6]
 [10 11 12]]
Slicing 03
 [[ 7  8  9]
 [10 11 12]]


In [67]:
# all 1s, 0s matrics
print(np.zeros((2, 2), dtype="int32"))
print(np.ones((2, 2), dtype="float16"))

# full
print(np.full(Array3D.shape, 69, "float32"))

# identity matrix
print(np.identity(4,dtype='int16'))

[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
[[[69. 69. 69.]
  [69. 69. 69.]]

 [[69. 69. 69.]
  [69. 69. 69.]]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [65]:
# random value matrix
print(np.random.rand(3,2))
print(np.random.randint(-4,8,size=(3,2)))


[[0.6064936  0.27779161]
 [0.78586364 0.11256445]
 [0.59665018 0.48248679]]
[[ 6  2]
 [ 3 -1]
 [-4  3]]


In [86]:
# Repeat array
repeatingArray = np.array([[[1,2],[3,4]]])
print('axis 0')
print(np.repeat(repeatingArray,2,axis=0))
print('\naxis 1')
print(np.repeat(repeatingArray,2,axis=1))
print('\naxis 2')
print(np.repeat(repeatingArray,2,axis=2))


axis 0
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

axis 1
[[[1 2]
  [1 2]
  [3 4]
  [3 4]]]

axis 2
[[[1 1 2 2]
  [3 3 4 4]]]


In [94]:
# copy
justAnArray = np.random.randint(0,3,(2,2))
RefCopied = justAnArray
ValueCopied = justAnArray.copy()
RefCopied[0,0] = 69
print(justAnArray,'\n',RefCopied,'\n',ValueCopied)



[[69  0]
 [ 2  2]] 
 [[69  0]
 [ 2  2]] 
 [[0 0]
 [2 2]]


In [103]:
# mathematic Uses
dummy1 = np.random.randint(0,9,(3,3))
dummy2 = np.random.randint(0,9,(3,3))
print(dummy1)
print('Substraction:\n',dummy1 - 1)
print('Multiplication:\n',dummy1 *dummy2)

dummySin = np.sin(dummy1)
dummySin



[[3 1 2]
 [4 6 1]
 [5 8 8]]
Substraction:
 [[2 0 1]
 [3 5 0]
 [4 7 7]]
Multiplication:
 [[ 9  2 14]
 [20  0  8]
 [25 16 40]]


array([[ 0.14112001,  0.84147098,  0.90929743],
       [-0.7568025 , -0.2794155 ,  0.84147098],
       [-0.95892427,  0.98935825,  0.98935825]])